name: Upload C# NuGet

on:
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [5.0.x]

    steps:
      - name: Build
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{matrix.dotnet-version}}

      - name: Install .NET Dependencies
        run: dotnet restore CSharp/CSharp.sln

      - name: Build .NET
        run: dotnet build CSharp/ --configuration ${{secrets.DOTNET_CONFIG}} --no-restore

      - name: Upload NuGet
        run: nuget push -Source https://api.nuget.org/v3/index.json -ApiKey ${{secrets.NUGET_API_KEY}} CSharp/Nocturnal-Devil.Ledger/bin/${{secrets.DOTNET_CONFIG}}/Nocturnal-Devil.Ledger.${{secrets.DOTNET_PACKAGE_VERSION}}.nupkg